development of bluegenes ESYN wrapper
intermine/bluegenes-esyn-viewer pull request #1
Opened 2020-07-16 10:27 UTC by Sakshisrivastava413

2020-08-10 15:48 UTC, heralden requested changes
Small change needed to `config.json`; otherwise looks good!

The example data gives `No interactions found. Have you tried expanding your search or using a different data source?` but this might be because Humanmine recently got a new release, changing the object IDs.

2020-08-10 15:48 UTC, uosl commented on config.json
> +  "accepts": ["id"],
I think this should be `ids` instead.

2020-08-11 08:00 UTC, Sakshisrivastava413 commented
> The example data gives `No interactions found. Have you tried expanding your search or using a different data source?` but this might be because Humanmine recently got a new release, changing the object IDs.

Right. That message comes from esyn.org as the passed objectIDs were not found.

2020-08-11 11:57 UTC, heralden approved these changes
Thanks, looks good now. :100:

2020-08-11 11:57 UTC, merged